### ISSUE TITLE
SSLError: SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED 

### ISSUE THREAD

**Issue by KawaneRio** [we-yu/sb.webscraping#15]
# 異臭
なんかエラーる

## 再現手順
1. clone repo
2. `cd /home/kawanerio/git/sb.webscraping/`
3. `python3 nicopedy_saver.py https://dic.nicovideo.jp/a/linux`

## 期待動作
- `./logs/[記事名].log`ファイルに掲示板ログがテキスト形式で保存される。

## 実際の挙動
- SSL Error

## ログ

```
kawanerio@MoebuntuStudio11:~/git/sb.webscraping$ python3 nicopedy_saver.py https://dic.nicovideo.jp/a/linux
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1017, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dic.nicovideo.jp', port=443): Max retries exceeded with url: /a/linux (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kawanerio/git/sb.webscraping/nicopedy_saver.py", line 227, in <module>
    art_req = requests.get(tgtArtUrl)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='dic.nicovideo.jp', port=443): Max retries exceeded with url: /a/linux (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))

```

## 環境

- Ubuntu 22.04.4 LTS
- Python 3.10.12

**Comment by KawaneRio** [comment]
Related? https://stackoverflow.com/questions/55680224/how-to-fix-requests-exceptions-sslerror

**Comment by KawaneRio** [comment]
これかも https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled

**Comment by KawaneRio** [comment]
`pip install cryptography==36.0.2` をしてみたが、だめだった。

<details><summary>log</summary><div>

```
kawanerio@MoebuntuStudio11:~/git/sb.webscraping$ pip install cryptography==36.0.2
Defaulting to user installation because normal site-packages is not writeable
Collecting cryptography==36.0.2
  Obtaining dependency information for cryptography==36.0.2 from https://files.pythonhosted.org/packages/01/86/4379b5eaafa5ea4b0081fa65a72849d6bba98e35c1da66f4b7a86878714d/cryptography-36.0.2-cp36-abi3-manylinux_2_24_x86_64.whl.metadata
  Downloading cryptography-36.0.2-cp36-abi3-manylinux_2_24_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3/dist-packages (from cryptography==36.0.2) (1.15.0)
Downloading cryptography-36.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 3.1 MB/s eta 0:00:00
Installing collected packages: cryptography
Successfully installed cryptography-36.0.2

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3 -m pip install --upgrade pip
kawanerio@MoebuntuStudio11:~/git/sb.webscraping$ python3 nicopedy_saver.py https://dic.nicovideo.jp/a/linux
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1017, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dic.nicovideo.jp', port=443): Max retries exceeded with url: /a/linux (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kawanerio/git/sb.webscraping/nicopedy_saver.py", line 227, in <module>
    art_req = requests.get(tgtArtUrl)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='dic.nicovideo.jp', port=443): Max retries exceeded with url: /a/linux (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))
```
</div></details>

**Comment by KawaneRio** [comment]
直りた。

https://stackoverflow.com/a/72245418 に基づき、以下のことをした：

# 手順

1. `/home/kawanerio/git/sb.webscraping/openssl.cnf` を作成。

2. `/home/kawanerio/git/sb.webscraping/openssl.cnf`へ以下の内容を保存する：

```
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = UnsafeLegacyRenegotiation
```

3. `OPENSSL_CONF=/home/kawanerio/git/sb.webscraping/openssl.cnf python3 nicopedy_saver.py https://dic.nicovideo.jp/a/linux`を實行する

### ログ

```
p/a/linux
pediLogFileName = [./logs/Linux.log]
Output log file = [ ./logs/Linux.log ]
Not found log file.
0 To 180
Minimum estimation time = 6s /  0m /  0h
Progress ... 30 60 90 120 150 176 
Output = ./logs/Linux.log ( 176 )
```

出力を無事確認。この異臭を閉ぢる。

ありがとう、ゑゆ殿。
